Clang Fix lots of warnings ../fs/quota/quota_tree.c:316:12: error: stack frame size (2192) exceeds limit (2048) in 'do_insert_tree' [-Werror,-Wframe-larger-than] static int do_insert_tree(struct qtree_mem_dqinfo *info, struct dquot *dquot,            ^ ../fs/quota/quota_tree.c:426:12: error: stack frame size (2144) exceeds limit (2048) in 'free_dqentry' [-Werror,-Wframe-larger-than] static int free_dqentry(struct qtree_mem_dqinfo *info, struct dquot *dquot,            ^ ../fs/quota/quota_tree.c:587:15: error: stack frame size (2128) exceeds limit (2048) in 'find_tree_dqentry' [-Werror,-Wframe-larger-than] static loff_t find_tree_dqentry(struct qtree_mem_dqinfo *info,               ^ 3 errors generated. Using a frame stack of 4kb fixes the complain. CONFIG_FRAME_WARN=4096
Change-Id: I8c344b92930f074ade453fd0a6e4e6d16df248b4
Signed-off-by: Panchajanya1999 <panchajanya@azure-dev.live>

../techpack/audio/ipc/apr.c:701:14: error: unused variable 'ptr'
[-Werror,-Wunused-variable]
                        uint32_t *ptr = data.payload;
                                  ^
1 error generated.
Change-Id: I26f9ccbd9833acc42758cb5f3decb303af250875
Signed-off-by: PainKiller3 <ninadpatil100@gmail.com>

../drivers/input/touchscreen/focaltech_touch/focaltech_core.c:864:21:
error: mixing declarations and code is a C99 extension
[-Werror,-Wdeclaration-after-statement]
        struct sched_param param = { .sched_priority = MAX_USER_RT_PRIO
/ 2 };
                           ^
1 error generated.

../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:118:5: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
    ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:46:3: note:
expanded from macro 'CYTTSP5_FW_UPGRADE'
        (defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_PLATFORM_FW_UPGRADE)
\
         ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:118:5: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:47:5: note:
expanded from macro 'CYTTSP5_FW_UPGRADE'
        ||
defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_BINARY_FW_UPGRADE))
           ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:128:5: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
    ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:46:3: note:
expanded from macro 'CYTTSP5_FW_UPGRADE'
        (defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_PLATFORM_FW_UPGRADE)
\
         ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:128:5: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:47:5: note:
expanded from macro 'CYTTSP5_FW_UPGRADE'
        ||
defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_BINARY_FW_UPGRADE))
           ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:128:27: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
                          ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:50:3: note:
expanded from macro 'CYTTSP5_TTCONFIG_UPGRADE'
        (defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_PLATFORM_TTCONFIG_UPGRADE)
\
         ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:128:27: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:51:5: note:
expanded from macro 'CYTTSP5_TTCONFIG_UPGRADE'
        ||
defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_MANUAL_TTCONFIG_UPGRADE))
           ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:233:5: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
    ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:46:3: note:
expanded from macro 'CYTTSP5_FW_UPGRADE'
        (defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_PLATFORM_FW_UPGRADE)
\
         ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:233:5: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:47:5: note:
expanded from macro 'CYTTSP5_FW_UPGRADE'
        ||
defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_BINARY_FW_UPGRADE))
           ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:829:5: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
    ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:50:3: note:
expanded from macro 'CYTTSP5_TTCONFIG_UPGRADE'
        (defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_PLATFORM_TTCONFIG_UPGRADE)
\
         ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:829:5: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:51:5: note:
expanded from macro 'CYTTSP5_TTCONFIG_UPGRADE'
        ||
defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_MANUAL_TTCONFIG_UPGRADE))
           ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:1361:6: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
     ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:46:3: note:
expanded from macro 'CYTTSP5_FW_UPGRADE'
        (defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_PLATFORM_FW_UPGRADE)
\
         ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:1361:6: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:47:5: note:
expanded from macro 'CYTTSP5_FW_UPGRADE'
        ||
defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_BINARY_FW_UPGRADE))
           ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:1381:5: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
    ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:46:3: note:
expanded from macro 'CYTTSP5_FW_UPGRADE'
        (defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_PLATFORM_FW_UPGRADE)
\
         ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:1381:5: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:47:5: note:
expanded from macro 'CYTTSP5_FW_UPGRADE'
        ||
defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_BINARY_FW_UPGRADE))
           ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:1492:5: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
    ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:46:3: note:
expanded from macro 'CYTTSP5_FW_UPGRADE'
        (defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_PLATFORM_FW_UPGRADE)
\
         ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:1492:5: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:47:5: note:
expanded from macro 'CYTTSP5_FW_UPGRADE'
        ||
defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_BINARY_FW_UPGRADE))
           ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:1503:5: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
    ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:46:3: note:
expanded from macro 'CYTTSP5_FW_UPGRADE'
        (defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_PLATFORM_FW_UPGRADE)
\
         ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:1503:5: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:47:5: note:
expanded from macro 'CYTTSP5_FW_UPGRADE'
        ||
defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_BINARY_FW_UPGRADE))
           ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:1503:27: error:
macro expansion producing 'defined' has undefined behavior
[-Werror,-Wexpansion-to-defined]
                          ^
../drivers/input/touchscreen/cyttsp5/cyttsp5_loader.c:50:3: note:
expanded from macro 'CYTTSP5_TTCONFIG_UPGRADE'
        (defined(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5_PLATFORM_TTCONFIG_UPGRADE)
\
         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

../drivers/input/touchscreen/cyttsp5/cyttsp5_device_access.c:1669:16:
error: use of logical '&&' with constant operand
[-Werror,-Wconstant-logical-operand]
        if (test_item && CM_ENABLED)
                      ^  ~~~~~~~~~~
../drivers/input/touchscreen/cyttsp5/cyttsp5_device_access.c:1669:16:
note: use '&' for a bitwise operation
        if (test_item && CM_ENABLED)
                      ^~
                      &
../drivers/input/touchscreen/cyttsp5/cyttsp5_device_access.c:1669:16:
note: remove constant to silence this warning
        if (test_item && CM_ENABLED)
                     ~^~~~~~~~~~~~~
../drivers/input/touchscreen/cyttsp5/cyttsp5_device_access.c:1673:16:
error: use of logical '&&' with constant operand
[-Werror,-Wconstant-logical-operand]
        if (test_item && CP_ENABLED)
                      ^  ~~~~~~~~~~
../drivers/input/touchscreen/cyttsp5/cyttsp5_device_access.c:1673:16:
note: use '&' for a bitwise operation
        if (test_item && CP_ENABLED)
                      ^~
                      &
../drivers/input/touchscreen/cyttsp5/cyttsp5_device_access.c:1673:16:
note: remove constant to silence this warning
        if (test_item && CP_ENABLED)
                     ~^~~~~~~~~~~~~
2 errors generated.
Fix compilation warnings and errors after enable LLVM.

Change-Id: I2d1209d008e85c2d856387644e5fcf5113b0e7af
Signed-off-by: Fei Mao <feim1@codeaurora.org>

../drivers/input/touchscreen/fts_521/fts_lib/ftsSoftware.h:27:17: error:
redefinition of typedef 'u8' is a C11 feature
[-Werror,-Wtypedef-redefinition]
typedef uint8_t u8;
/*basic type that represent one byte (or 8 bits)*/
                ^
../include/asm-generic/int-ll64.h:16:23: note: previous definition is
here
typedef unsigned char u8;
                      ^
In file included from ../drivers/input/touchscreen/fts_521/fts.c:73:
In file included from ../drivers/input/touchscreen/fts_521/fts.h:39:
../drivers/input/touchscreen/fts_521/fts_lib/ftsSoftware.h:28:18: error:
redefinition of typedef 'u16' is a C11 feature
[-Werror,-Wtypedef-redefinition]
typedef uint16_t u16;
/*basic type that represent 2 bytes (or 16 bits)*/
                 ^
../include/asm-generic/int-ll64.h:19:24: note: previous definition is
here
typedef unsigned short u16;
                       ^
In file included from ../drivers/input/touchscreen/fts_521/fts.c:73:
In file included from ../drivers/input/touchscreen/fts_521/fts.h:39:
../drivers/input/touchscreen/fts_521/fts_lib/ftsSoftware.h:29:18: error:
redefinition of typedef 'u32' is a C11 feature
[-Werror,-Wtypedef-redefinition]
typedef uint32_t u32;
/*basic type that represent 4 bytes (or 32 bits)*/
                 ^
../include/asm-generic/int-ll64.h:22:22: note: previous definition is
here
typedef unsigned int u32;
                     ^
In file included from ../drivers/input/touchscreen/fts_521/fts.c:73:
In file included from ../drivers/input/touchscreen/fts_521/fts.h:39:
../drivers/input/touchscreen/fts_521/fts_lib/ftsSoftware.h:30:18: error:
redefinition of typedef 'u64' is a C11 feature
[-Werror,-Wtypedef-redefinition]
typedef uint64_t u64;
/*basic type that represent 8 bytes (or 64 bits)*/
                 ^
../include/asm-generic/int-ll64.h:25:28: note: previous definition is
here
typedef unsigned long long u64;
                           ^
../drivers/input/touchscreen/fts_521/fts.c:239:29: error: 'sscanf' may
overflow; destination buffer in argument 3 has size 100, but the
corresponding specifier may require size 101 [-Werror,-Wfortify-source]
        sscanf(buf, "%100s %d %d", path, &mode[0], &mode[1]);
                                   ^
../drivers/input/touchscreen/fts_521/fts.c:4188:31: error: equality
comparison with extraneous parentheses [-Werror,-Wparentheses-equality]
                if ((info->lockdown_info[0] ==
                     ~~~~~~~~~~~~~~~~~~~~~~~^~
../drivers/input/touchscreen/fts_521/fts.c:4188:31: note: remove
extraneous parentheses around the comparison to silence this warning
                if ((info->lockdown_info[0] ==
                    ~                       ^
../drivers/input/touchscreen/fts_521/fts.c:4188:31: note: use '=' to
turn this equality comparison into an assignment
                if ((info->lockdown_info[0] ==
                                            ^~
                                            =
../drivers/input/touchscreen/fts_521/fts.c:4220:31: error: equality
comparison with extraneous parentheses [-Werror,-Wparentheses-equality]
                if ((info->lockdown_info[0] ==
                     ~~~~~~~~~~~~~~~~~~~~~~~^~
../drivers/input/touchscreen/fts_521/fts.c:4220:31: note: remove
extraneous parentheses around the comparison to silence this warning
                if ((info->lockdown_info[0] ==
                    ~                       ^
../drivers/input/touchscreen/fts_521/fts.c:4220:31: note: use '=' to
turn this equality comparison into an assignment
                if ((info->lockdown_info[0] ==
                                            ^~
                                            =
../drivers/input/touchscreen/fts_521/fts.c:4341:17: error: equality
comparison with extraneous parentheses [-Werror,-Wparentheses-equality]
        if ((init_type == NO_INIT)) {
             ~~~~~~~~~~^~~~~~~~~~
../drivers/input/touchscreen/fts_521/fts.c:4341:17: note: remove
extraneous parentheses around the comparison to silence this warning
        if ((init_type == NO_INIT)) {
            ~          ^         ~
../drivers/input/touchscreen/fts_521/fts.c:4341:17: note: use '=' to
turn this equality comparison into an assignment
        if ((init_type == NO_INIT)) {
                       ^~
                       =
8 errors generated.

../drivers/input/touchscreen/fts_521/fts.c:239:29: error: 'sscanf' may
overflow; destination buffer in argument 3 has size 100, but the
corresponding specifier may require size 101 [-Werror,-Wfortify-source]
        sscanf(buf, "%100s %d %d", path, &mode[0], &mode[1]);
                                   ^
../drivers/input/touchscreen/nt36xxx/nt36xxx.c:1120:5: error:
'NVT_TOUCH_ESD_PROTECT' is not defined, evaluates to 0 [-Werror,-Wundef]
    ^
../drivers/input/touchscreen/nt36xxx/nt36xxx.c:1087:21: error: mixing
declarations and code is a C99 extension
[-Werror,-Wdeclaration-after-statement]
        struct sched_param param = { .sched_priority = MAX_USER_RT_PRIO
/ 2 };
                           ^
2 errors generated.

../drivers/gpu/drm/msm/msm_gem.c:1080:1: error: unused label 'fail'
[-Werror,-Wunused-label]
fail:
^~~~~
1 error generated.
Signed-off-by: Rama Bondan Prakoso <ramanarubp@gmail.com>

The macro results are assigned to u8 variables/fields. Adding the cast
fixes plenty of clang warnings about "implicit conversion from 'int' to
'u8'".
../drivers/net/wireless/ath/ath9k/ar9003_eeprom.c:563:39: error:
implicit conversion from 'int' to 'u8' (aka 'unsigned char') changes
value from 3495 to 167 [-Werror,-Wconstant-conversion]
/* Data[8].ctlEdges[7].bChannel */ FREQ2FBIN(5795, 0)

../drivers/pci/host/pci-msm.c:6271:25: error: unused variable 'pcie_dev'
[-Werror,-Wunused-variable]
        struct msm_pcie_dev_t *pcie_dev = PCIE_BUS_PRIV_DATA(dev->bus);
                               ^
1 error generated.
Signed-off-by: CloudedQuartz <ravenklawasd@gmail.com>

../drivers/slimbus/slim-msm-ngd.c:1030:24: error: unused variable 'dev'
[-Werror,-Wunused-variable]
        struct msm_slim_ctrl *dev = slim_get_ctrldata(ctrl);
                              ^
1 error generated.

../drivers/soc/qcom/glink_loopback_server.c:812:18: error: unused
variable 'tx_done_ch_info' [-Werror,-Wunused-variable]
        struct ch_info *tx_done_ch_info = (struct ch_info *)priv;
                        ^
1 error generated.

../drivers/usb/gadget/function/rndis.c:1105:16: error: unused variable
'flags' [-Werror,-Wunused-variable]
        unsigned long flags;
                      ^
../drivers/usb/gadget/function/rndis.c:1144:16: error: unused variable
'flags' [-Werror,-Wunused-variable]
        unsigned long flags;
                      ^
2 errors generated.